version: "3"

services:
  api-solid-database:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=api-solid
      - POSTGRESQL_PASSWORD=Lo159c@17
      - POSTGRESQL_DATABASE=apisolid
